### ISSUE TITLE
can't set correct time

### ISSUE THREAD

**Issue by HerrFrutti** [MatthewVance/unbound-docker-rpi#23]
Error:
```

[-1227173427] unbound[1:1] error: gettimeofday: Operation not permitted
```
if you get the time inside the container:
```
root@unbound:/opt/unbound# date
Thu Jan  1 01:00:00 CET 1970
root@unbound:/opt/unbound# zdump /etc/localtime 
/etc/localtime  Fri Feb 27 19:29:32 1970 CET
root@unbound:/opt/unbound# cat /etc/timezone 
Europe/Berlin
```
my docker compose:
```yaml
unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    hostname: unbound
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      macvlan-nw:
        ipv4_address: 192.168.X.X
    restart: always
```
I don't know how to get the correct time inside the container...  
And that leads to DNSSEC -> SERVFAIL
```bash
$ dig sigok.verteiltesysteme.net @192.168.X.X

; <<>> DiG 9.10.6 <<>> sigok.verteiltesysteme.net @192.168.X.X
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59399
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;sigok.verteiltesysteme.net.	IN	A

;; Query time: 10 msec
;; SERVER: 192.168.X.X#53(192.168.X.X)
;; WHEN: Sun Jan 09 00:14:26 CET 2022
;; MSG SIZE  rcvd: 55
```
