### ISSUE TITLE
Cloudflare.com querys every 30 seconds

### ISSUE THREAD

**Issue by loeffelpan** [MatthewVance/unbound-docker-rpi#41]
**Describe the bug**
Unbound queries `cloudflare.com` every 30 seconds via pihole (seen in piholes query logs). Pihole is configured as system-wide dns.

**To Reproduce**
1. Docker run command or compose file:
```
version: '3'
services:
  unbound:
  container_name: unbound
  restart: unless-stopped
  volumes:
    - ./etc-unbound:/opt/unbound/etc/unbound
    - /dev/log:/dev/log
  image: mvance/unbound:latest
  network_mode: host
```
2. Customizations (config files):
```
server:

  verbosity: 1
  port: 5335
  do-ip4: yes
  do-ip6: no

  hide-identity: yes
  hide-version: yes
  hide-trustanchor: yes
  prefetch: yes

  num-threads: 1

  private-address: 192.168.0.0/16
  private-address: 169.254.0.0/16
  private-address: 172.16.0.0/12
  private-address: 10.0.0.0/8
  private-domain: mydns.jdownloader.org
```
3. cloudflare.com is queried every 30 seconds.
4. Stopping unbound container and no further queries are gone.

**Expected behavior**
No constant queries to cloudflare.com.

**Additional context**
Please review also #1 and #14 .
In #1 there is Cloudflare configured as forward-dns, but healthcheck should check 1.1.1.1 and 1.0.0.1 and not cloudflared.com.
In #14 there's only quad9 configured as forward-dns and also cloudflare.com querys are seen.
